In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train , y_train),(x_test , y_test) = mnist.load_data()
x_train , x_test = x_train/255.0, x_test/255.0

In [3]:
model = tf.keras.Sequential([tf.keras.layers.Flatten(input_shape = (28,28)),
                             tf.keras.layers.Dense(128, activation = "relu"),
                             tf.keras.layers.Dense(10)])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.05199247,  0.41355968, -0.64074194,  0.10320183, -0.49797404,
        -0.15306643,  0.39555457,  0.88014495, -0.14519963,  0.15988384]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.09079435, 0.1303423 , 0.04541592, 0.09556497, 0.05238553,
        0.07396101, 0.12801649, 0.20783603, 0.07454514, 0.10113825]],
      dtype=float32)

In [6]:
loss_fun = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fun(y_train[:1], predictions).numpy()

2.604217

In [8]:
model.compile(optimizer="adam",
             loss = loss_fun,
             metrics = ["accuracy"])

In [9]:
model.fit(x_train , y_train , epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2620 - accuracy: 0.9261
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1142 - accuracy: 0.9664
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0784 - accuracy: 0.9764
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0596 - accuracy: 0.9822
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0460 - accuracy: 0.9857


In [10]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0787 - accuracy: 0.9755 - 704ms/epoch - 2ms/step


[0.07865455746650696, 0.9754999876022339]

In [11]:
probability_model = tf.keras.Sequential([model, 
                                        tf.keras.layers.Softmax()
                                        ])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.5924504e-08, 1.4584153e-09, 1.2688328e-06, 1.6540920e-04,
        2.0296297e-10, 1.6735148e-08, 4.0567723e-12, 9.9983156e-01,
        1.1113078e-06, 4.9849154e-07],
       [1.9147667e-08, 2.1336823e-06, 9.9997783e-01, 7.0321967e-06,
        5.9095551e-14, 1.2378974e-05, 2.8983475e-08, 1.4287076e-15,
        5.9040110e-07, 1.2238870e-13],
       [1.8128758e-05, 9.9683654e-01, 8.2190207e-05, 8.7930246e-05,
        2.2471127e-04, 1.6440659e-05, 2.0140635e-05, 6.6197402e-04,
        2.0271274e-03, 2.4786401e-05],
       [9.9994648e-01, 2.7397443e-10, 5.9665667e-06, 3.0877217e-08,
        1.7254798e-08, 4.1326680e-06, 3.0337387e-05, 1.2788356e-05,
        6.9175661e-09, 2.2744914e-07],
       [6.1274086e-08, 3.5273777e-11, 2.7432332e-08, 5.3630433e-09,
        9.9801958e-01, 7.4736398e-08, 6.8326720e-08, 9.1761185e-06,
        1.4279595e-07, 1.9707140e-03]], dtype=float32)>